name: posia_module_butcher
description: Modulo vertical carniceria con venta por peso para POSIA.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  posia_core:
    path: ../posia_core
  posia_hardware:
    path: ../posia_hardware

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
