name: posia_sync
description: Sincronizacion hub central y LAN para POSIA.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  http: ^1.6.0
  posia_core:
    path: ../posia_core

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
