/// Barrel export del nucleo de dominio POSIA.
///
/// Autor: Equipo POSIA
/// Matricula: POSIA-2026-001
/// Fecha creacion: 2026-06-07 18:30:00 (UTC-6)
/// Ultima modificacion: 2026-06-07 18:30:00 (UTC-6)
library;

export 'src/config/configuracion_entorno.dart';
export 'src/constants/posia_constants.dart';
export 'src/constants/configuracion_despliegue.dart';
export 'src/constants/motivos_inventario.dart';
export 'src/enums/alcance_precio_venta.dart';
export 'src/enums/canal_venta.dart';
export 'src/enums/condicion_descuento_cliente.dart';
export 'src/enums/tipo_descuento_cliente.dart';
export 'src/enums/estado_pedido.dart';
export 'src/enums/estado_sync_evento.dart';
export 'src/enums/estado_traspaso.dart';
export 'src/enums/estado_turno_caja.dart';
export 'src/enums/estado_venta.dart';
export 'src/enums/metodo_pago.dart';
export 'src/enums/modulo_licencia.dart';
export 'src/enums/modulo_vertical.dart';
export 'src/enums/nivel_alerta_caducidad.dart';
export 'src/enums/modo_calculo_utilidad.dart';
export 'src/enums/regla_precio.dart';
export 'src/enums/rol_usuario.dart';
export 'src/enums/tipo_movimiento_inventario.dart';
export 'src/enums/tipo_sync_evento.dart';
export 'src/enums/unidad_medida.dart';
export 'src/models/categoria.dart';
export 'src/models/cliente.dart';
export 'src/models/cobro_request.dart';
export 'src/models/compra.dart';
export 'src/models/cotizacion.dart';
export 'src/models/contexto_precio.dart';
export 'src/models/descuento_cliente.dart';
export 'src/models/filtro_ventas.dart';
export 'src/models/linea_carrito.dart';
export 'src/models/linea_ticket_espera.dart';
export 'src/models/movimiento_inventario.dart';
export 'src/models/almacen.dart';
export 'src/models/asistencia.dart';
export 'src/models/nomina.dart';
export 'src/models/presentacion_producto.dart';
export 'src/models/pedido.dart';
export 'src/models/proveedor.dart';
export 'src/models/linea_pedido.dart';
export 'src/models/linea_cotizacion.dart';
export 'src/models/linea_venta.dart';
export 'src/models/lote_farmacia.dart';
export 'src/models/lista_precios.dart';
export 'src/models/producto.dart';
export 'src/models/resumen_cliente.dart';
export 'src/models/resumen_producto_venta.dart';
export 'src/models/resumen_ventas_hora.dart';
export 'src/models/resultado_precio.dart';
export 'src/models/stock_nivel.dart';
export 'src/models/sync_event.dart';
export 'src/models/tienda.dart';
export 'src/models/ticket_digital.dart';
export 'src/models/ticket_en_espera.dart';
export 'src/models/traspaso.dart';
export 'src/models/usuario.dart';
export 'src/models/turno_caja.dart';
export 'src/models/variante_producto.dart';
export 'src/models/vendedor.dart';
export 'src/models/venta.dart';
export 'src/utils/busqueda_producto_util.dart';
export 'src/utils/cliente_credito_util.dart';
export 'src/utils/etiquetas_descuento_cliente.dart';
export 'src/utils/geolocalizacion_util.dart';
export 'src/utils/formateador_ticket_digital.dart';
export 'src/utils/generador_ticket.dart';
export 'src/utils/hasher_pin.dart';
export 'src/utils/id_posia.dart';
export 'src/utils/permisos_usuario.dart';
export 'src/utils/validador_codigo_usuario.dart';
export 'src/utils/moneda_util.dart';
export 'src/utils/traspaso_util.dart';
export 'src/utils/precio_util.dart';
export 'src/repositories/repositorio_lote_farmacia.dart';
export 'src/vertical/servicio_farmacia.dart';
export 'src/vertical/util_peso.dart';
